---
# Name of the Project
ProjectName: 'Gerald Test'

# Project Id, only alphanumerical characters allowed.
ProjectId: 'gerald'

# Domain to use for OpenShift. Must have an existing Route53 hosted zone
Domain: cc-openshift.de

# Cluster Id to identify AWS cluster resources. Can be anything.
ClusterId: '1'

# Persistence Storage configuration
Storage:
  # Enable EFS as persistence storage provider
  EnableEfs: true
  # Encrypt EFS using KMS
  EncryptEfs: true

  # Enable EBS as persistence storage provider
  EnableEbs: true
  # Encrypt EBS volumes using KMS
  EncryptEbs: true

  # Default storage provider. Should be either efs or ebs
  Default: ebs

# Enable aggregated logging. Automatically installs ElasticSearch, FluentD and Kibana
# See: https://docs.openshift.org/latest/install_config/aggregate_logging.html
AggregatedLogging: false

# Enable cluster metrics collection
# See: https://docs.openshift.org/latest/install_config/cluster_metrics.html
ClusterMetrics: false

# Configure Docker to storage container registry in S3 bucket. Bucket will be automatically generated
# This feature provides significant performance improvements
RegistryToS3: true

# Number of cluster nodes
# Warning: The number of nodes has significant influence on costs
NodeCounts:
  # Number of Master Nodes
  Master: 1
  # Number of Infrastructure Nodes
  Infra: 3
  # Number of Application Nodes
  App: 3

# EC2 instance types to use for particular node types
# Warning: Node Types have significant influence on costs
# See: https://aws.amazon.com/en/ec2/instance-types/
NodeTypes:
  Bastion: 't2.nano'
  Master: 'm5.large'
  Infra: 't2.medium'
  App: 't2-medium'

# AWS configuration options
AwsConfig:
  # Region to create the cluster in
  # Valid values: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
  Region: eu-central-1

  # AWS Access key credentials
  # Can be left empty, when there is a configure aws cli client on the host system
  # Can be left empty, when running inside an EC2 instance with "AdministratorAccess" Policy
  # Can be left empty, when access key is provided using command line options
  KeyId: ''
  SecretKey: ''
